name: 'Terraform Apply and Summary'
description: 'Applies Terraform plan and writes a grouped resource summary with IDs and timestamp to GitHub Step Summary.'

inputs:
  artifact-name:
    description: 'Name of the uploaded Terraform plan artifact'
    required: true
    default: 'terraform-plan'

  release_tag:
    description: 'Optional release tag to checkout'
    required: false
    type: string
    default: ''

  terraform-dir:
    description: "Path to the Terraform configuration"
    required: false
    default: "tf"

  s3-bucket:
    description: "S3 bucket for Terraform backend"
    required: true

  s3-region:
    description: "AWS region where the S3 bucket is located"
    required: true

  ci-pipeline:
    description: "Set to true to use commit SHA in backend key"
    required: false
    default: "false"

runs:
  using: 'composite'
  steps:

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.release_tag || github.ref_name }}       

    - name: Download Terraform plan artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: plan-artifact

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Compute Backend Key from Repository Name
      id: key
      shell: bash
      run: |
        if [[ "${{ inputs.ci-pipeline }}" == "true" ]]; then
          state_key="${{ github.repository }}/${{ github.sha }}/terraform.tfstate"
        else
          state_key="${{ github.repository }}/terraform.tfstate"
        fi
        echo "s3_key=$state_key" >> $GITHUB_OUTPUT

    - name: Terraform Init with S3 Backend
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.terraform-dir }}
      run: |
        terraform init -input=false \
          -backend-config="bucket=${{ inputs.s3-bucket }}" \
          -backend-config="key=${{ steps.key.outputs.s3_key }}" \
          -backend-config="region=${{ inputs.s3-region }}" \
          -backend-config="encrypt=true" \
          -backend-config="use_lockfile=true"

    - name: Terraform Apply
      id: apply
      working-directory: ${{ github.workspace }}/${{ inputs.terraform-dir }}
      run: |
        cp ../plan-artifact/${{ inputs.terraform-plan-file }} tfplan.out

        TIMESTAMP=$(date -u "+%Y-%m-%d %H:%M:%S UTC")

        echo "## 🚀 Terraform Apply Output" >> "$GITHUB_STEP_SUMMARY"
        echo "_**Started at: ${TIMESTAMP}**_" >> "$GITHUB_STEP_SUMMARY"
        echo "" >> "$GITHUB_STEP_SUMMARY"

        terraform apply -input=false -auto-approve tfplan.out || exit 1

        echo "" >> "$GITHUB_STEP_SUMMARY"
        echo "### Affected Resources from Plan JSON" >> "$GITHUB_STEP_SUMMARY"
        echo "" >> "$GITHUB_STEP_SUMMARY"
        echo "| Resource Address        | Action     | Resource Type     | Resource Name     | Timestamp               |" >> "$GITHUB_STEP_SUMMARY"
        echo "|--------------------------|------------|--------------------|--------------------|--------------------------|" >> "$GITHUB_STEP_SUMMARY"

        # Terraform Outputs Section
        echo "" >> "$GITHUB_STEP_SUMMARY"
        echo "### Terraform Outputs" >> "$GITHUB_STEP_SUMMARY"
        echo "" >> "$GITHUB_STEP_SUMMARY"

        terraform output -json > tf_output.json

        echo "| Name | Value |" >> "$GITHUB_STEP_SUMMARY"
        echo "|------|-------|" >> "$GITHUB_STEP_SUMMARY"

        jq -r 'to_entries[] | 
          "| \(.key) | \(.value.value)"' tf_output.json >> "$GITHUB_STEP_SUMMARY"

        echo "" >> "$GITHUB_STEP_SUMMARY"
        TIMESTAMP=$(date -u "+%Y-%m-%d %H:%M:%S UTC")
        echo "_**Completed at: ${TIMESTAMP}**_" >> "$GITHUB_STEP_SUMMARY"
        echo "" >> "$GITHUB_STEP_SUMMARY"
      shell: bash
