name: 'Terraform Apply and Summary'
description: 'Applies Terraform plan and writes a grouped resource summary with IDs and timestamp to GitHub Step Summary.'

inputs:

  terraform-dir:
    description: "Relative path to the directory containing Terraform configuration files (e.g., 'tf', 'infrastructure')."
    required: false
    type: string
    default: "tf"

  release-tag:
    description: "Git release tag to check out. If omitted, the latest commit on the default branch is used."
    required: false
    type: string
    default: ""

  ci-pipeline:
    description: "Set to 'true' to include the commit SHA in the Terraform state key (suitable for CI/CD). Use 'false' for static state keys."
    required: false
    type: string
    default: "false"

  s3-bucket:
    description: "Name of the S3 bucket used as the backend for storing the Terraform state file."
    required: true
    type: string

  s3-region:
    description: "AWS region where the S3 backend bucket is located (e.g., us-east-1, eu-west-1)."
    required: true
    type: string

  tf-plan-name:
    description: "Name of the Terraform plan file"
    required: false
    default: "terraform-plan"

  tf-plan-file:
    description: "File to save the Terraform plan output"
    required: false
    default: "tfplan"  

  tf-vars-file:
    description: "Optional Terraform variable file"
    required: false
    default: "terraform.tfvars"

runs:
  using: "composite"
  steps:

    - name: Set Checkout Ref
      id: set-ref
      shell: bash
      run: |
        if [[ -n "${{ inputs.release-tag }}" ]]; then
          echo "ref=${{ inputs.release-tag }}" >> $GITHUB_OUTPUT
        else
          echo "ref=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
        fi

    - name: Checkout Repo
      id: checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.set-ref.outputs.ref }}

    - name: Download Terraform plan artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.terraform-plan-file }}
        path: ${{ inputs.tf-plan-name}}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Generate Terraform State Key
      id: generate-tfstate-key
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.terraform-dir }}
      run: |
        if [[ "${{ inputs.ci-pipeline }}" == "true" ]]; then
          state_key="${{ github.repository }}/${{ github.sha }}/terraform.tfstate"
        else
          state_key="${{ github.repository }}/terraform.tfstate"
        fi
        echo "s3_key=$state_key" >> $GITHUB_OUTPUT

    - name: Initialize Terraform with S3 Backend
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.terraform-dir }}
      run: |
        terraform init -input=false \
          -backend-config="bucket=${{ inputs.s3-bucket }}" \
          -backend-config="key=${{ steps.generate-tfstate-key.outputs.s3_key }}" \
          -backend-config="region=${{ inputs.s3-region }}" \
          -backend-config="encrypt=true" \
          -backend-config="use_lockfile=true"

    - name: Download Plan Output as Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.tf-plan-name }}
        path: ${{ github.workspace }}/${{ inputs.terraform-dir }}

    - name: Terraform Apply with Summary
      id: apply
      working-directory: ${{ github.workspace }}/${{ inputs.terraform-dir }}
      shell: bash
      run: |
        pwd
        echo "=========================="
        ls -alrt
        echo "=========================="
        cat ${{ inputs.tf-plan-file }}.out
        
        # Check if the plan file exists
        if [ ! -f tfplan.out ]; then
          echo "❌ Plan file not found. Exiting."
          exit 1
        fi

        echo "Available Terraform files: "
        echo "-----------------------------"
        ls -lR

        echo "---------Terraform Var file--------------------"
        cat ${{ inputs.tf-vars-file }}

        START_TIME=$(date -u "+%Y-%m-%d %H:%M:%S UTC")
        echo "## 🚀 Terraform Apply Output" >> "$GITHUB_STEP_SUMMARY"
        echo "_**Started at: ${START_TIME}**_" >> "$GITHUB_STEP_SUMMARY"
        echo "" >> "$GITHUB_STEP_SUMMARY"

        # Apply the saved plan
        terraform apply -input=false -auto-approve tfplan.out

        echo "" >> "$GITHUB_STEP_SUMMARY"
        echo "### 📌 Affected Resources" >> "$GITHUB_STEP_SUMMARY"
        echo "" >> "$GITHUB_STEP_SUMMARY"
        echo "| Resource Address | Action | Resource Type | Resource Name |" >> "$GITHUB_STEP_SUMMARY"
        echo "|------------------|--------|---------------|----------------|" >> "$GITHUB_STEP_SUMMARY"

        # Parse affected resources from the plan
        terraform show -json tfplan.out | jq -r '
          .resource_changes[] | 
          select(.change.actions != ["no-op"]) |
          "| \(.address) | \(.change.actions[0]) | \(.type) | \(.name) |"
        ' >> "$GITHUB_STEP_SUMMARY"

        echo "" >> "$GITHUB_STEP_SUMMARY"
        echo "### 📤 Terraform Outputs" >> "$GITHUB_STEP_SUMMARY"
        echo "" >> "$GITHUB_STEP_SUMMARY"

        terraform output -json > tf_output.json

        echo "| Name | Value |" >> "$GITHUB_STEP_SUMMARY"
        echo "|------|-------|" >> "$GITHUB_STEP_SUMMARY"

        jq -r 'to_entries[] | 
          "| \(.key) | \(.value.value)"' tf_output.json >> "$GITHUB_STEP_SUMMARY"

        echo "" >> "$GITHUB_STEP_SUMMARY"
        END_TIME=$(date -u "+%Y-%m-%d %H:%M:%S UTC")
        echo "_**Completed at: ${END_TIME}**_" >> "$GITHUB_STEP_SUMMARY"

